container:
  image: golang:latest

env:
  GOPROXY: https://proxy.golang.org

task:
  name: Test
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  get_script: go get ./...
  build_script: go build ./...
  test_script: go test ./...