container:
  image: golang:latest

env:
  GOPROXY: https://proxy.golang.org

task:
  name: Test
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  get_script: go get ./...
  build_script: go build ./...
  test_script: go test ./...
  
task:
  name: Build Binaries
  only_if: $CIRRUS_PR != ''
  depends_on: Test
  container:
    image: goreleaser/goreleaser:latest
  release_script: goreleaser --build --snapshot
  binaries_artifacts:
    path: "dist/agent_*/agent*"

task:
  name: Release
  only_if: $CIRRUS_TAG != ''
  depends_on: Test
  env:
    GITHUB_TOKEN: ENCRYPTED[!98ace8259c6024da912c14d5a3c5c6aac186890a8d4819fad78f3e0c41a4e0cd3a2537dd6e91493952fb056fa434be7c!]
  container:
    image: goreleaser/goreleaser:latest
  release_script: goreleaser
