linters:
  disable:
    # These generate too much errors and are disabled for now.
    - errcheck

issues:
  # Don't hide multiple issues that belong to one class since GitHub annotations can handle them all nicely.
  max-issues-per-linter: 0
  max-same-issues: 0
