project_name: agent

before:
  hooks:
    - go mod download
    
archives:
  - format: binary

builds:
  - main: cmd/agent/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - solaris
    goarch:
      - amd64
      - arm
      - arm64
      - s390x
      - ppc64le
