project_name: agent

before:
  hooks:
    - go mod download

archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: regular
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

builds:
  - id: "agent"
    main: cmd/agent/main.go
    ldflags: -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - freebsd
      - openbsd
      - netbsd
      - solaris
    goarch:
      - amd64
      - arm
      - arm64
      - s390x
      - ppc64le
  - id: "agent_cgo"
    main: cmd/agent/main.go
    ldflags: -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

release:
  prerelease: auto
