project_name: agent

before:
  hooks:
    - go mod download

archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: regular
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

builds:
  - main: cmd/agent/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - solaris
    goarch:
      - amd64
      - arm
      - arm64
      - s390x
      - ppc64le

release:
  prerelease: auto
