steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cirrus-ci-community/cirrus-ci-agent:$TAG_NAME', '-t', 'gcr.io/cirrus-ci-community/cirrus-ci-agent:latest', '.']
images: ['gcr.io/cirrus-ci-community/cirrus-ci-agent:$TAG_NAME', 'gcr.io/cirrus-ci-community/cirrus-ci-agent:latest']
