steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--privileged', '--rm', 'tonistiigi/binfmt', '--install', 'all']
    id: 'initialize-qemu'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--name', 'mybuilder']
    id: 'create-builder'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'use', 'mybuilder']
    id: 'select-builder'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'inspect', '--bootstrap']
    id: 'show-target-build-platforms'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'build', '--platform', 'linux/amd64,linux/arm64', '-t', 'gcr.io/cirrus-ci-community/cirrus-ci-agent:$TAG_NAME', '-t', 'gcr.io/cirrus-ci-community/cirrus-ci-agent:latest', '--push', '.']
    id: 'build-multi-architecture-container-image'
options:
  env:
    # to use buildx for multiarch build via buildx
    - 'DOCKER_CLI_EXPERIMENTAL=enabled'
timeout: 3600s
